# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jackson Struthers
email: jacksonstruthers@gmail.com
description: Web Design Portfolio 2016
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jstruthers.github.io" # the base hostname & protocol for your site
github_username:  jstruthers

# Collections
collections:
- projects
- case-studies

# Build settings
markdown: kramdown
